//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4CSharpConsoleApplicationUppg2.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Restaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string openHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mailAdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string foodTypeField;
        
        private int priceClassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string restaurantID {
            get {
                return this.restaurantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantIDField, value) != true)) {
                    this.restaurantIDField = value;
                    this.RaisePropertyChanged("restaurantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string restaurantName {
            get {
                return this.restaurantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantNameField, value) != true)) {
                    this.restaurantNameField = value;
                    this.RaisePropertyChanged("restaurantName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string restaurantAdress {
            get {
                return this.restaurantAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantAdressField, value) != true)) {
                    this.restaurantAdressField = value;
                    this.RaisePropertyChanged("restaurantAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string restaurantCity {
            get {
                return this.restaurantCityField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantCityField, value) != true)) {
                    this.restaurantCityField = value;
                    this.RaisePropertyChanged("restaurantCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string openHours {
            get {
                return this.openHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.openHoursField, value) != true)) {
                    this.openHoursField = value;
                    this.RaisePropertyChanged("openHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneNumberField, value) != true)) {
                    this.phoneNumberField = value;
                    this.RaisePropertyChanged("phoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mailAdress {
            get {
                return this.mailAdressField;
            }
            set {
                if ((object.ReferenceEquals(this.mailAdressField, value) != true)) {
                    this.mailAdressField = value;
                    this.RaisePropertyChanged("mailAdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string foodType {
            get {
                return this.foodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.foodTypeField, value) != true)) {
                    this.foodTypeField = value;
                    this.RaisePropertyChanged("foodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int priceClass {
            get {
                return this.priceClassField;
            }
            set {
                if ((this.priceClassField.Equals(value) != true)) {
                    this.priceClassField = value;
                    this.RaisePropertyChanged("priceClass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableReservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TableReservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reservationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string personNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string personMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string personPhoneNumberField;
        
        private int guestAmountField;
        
        private System.DateTime reservationDateField;
        
        private System.DateTime reservationTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string reservationID {
            get {
                return this.reservationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.reservationIDField, value) != true)) {
                    this.reservationIDField = value;
                    this.RaisePropertyChanged("reservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dtableID {
            get {
                return this.dtableIDField;
            }
            set {
                if ((object.ReferenceEquals(this.dtableIDField, value) != true)) {
                    this.dtableIDField = value;
                    this.RaisePropertyChanged("dtableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string personName {
            get {
                return this.personNameField;
            }
            set {
                if ((object.ReferenceEquals(this.personNameField, value) != true)) {
                    this.personNameField = value;
                    this.RaisePropertyChanged("personName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string personMail {
            get {
                return this.personMailField;
            }
            set {
                if ((object.ReferenceEquals(this.personMailField, value) != true)) {
                    this.personMailField = value;
                    this.RaisePropertyChanged("personMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string personPhoneNumber {
            get {
                return this.personPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.personPhoneNumberField, value) != true)) {
                    this.personPhoneNumberField = value;
                    this.RaisePropertyChanged("personPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int guestAmount {
            get {
                return this.guestAmountField;
            }
            set {
                if ((this.guestAmountField.Equals(value) != true)) {
                    this.guestAmountField = value;
                    this.RaisePropertyChanged("guestAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime reservationDate {
            get {
                return this.reservationDateField;
            }
            set {
                if ((this.reservationDateField.Equals(value) != true)) {
                    this.reservationDateField = value;
                    this.RaisePropertyChanged("reservationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime reservationTime {
            get {
                return this.reservationTimeField;
            }
            set {
                if ((this.reservationTimeField.Equals(value) != true)) {
                    this.reservationTimeField = value;
                    this.RaisePropertyChanged("reservationTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DiningTable", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DiningTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtableIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantIDField;
        
        private int seatAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dtableID {
            get {
                return this.dtableIDField;
            }
            set {
                if ((object.ReferenceEquals(this.dtableIDField, value) != true)) {
                    this.dtableIDField = value;
                    this.RaisePropertyChanged("dtableID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string restaurantID {
            get {
                return this.restaurantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantIDField, value) != true)) {
                    this.restaurantIDField = value;
                    this.RaisePropertyChanged("restaurantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int seatAmount {
            get {
                return this.seatAmountField;
            }
            set {
                if ((this.seatAmountField.Equals(value) != true)) {
                    this.seatAmountField = value;
                    this.RaisePropertyChanged("seatAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RestaurantRating", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class RestaurantRating : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ratingIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string restaurantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reviewerNameField;
        
        private float ratingScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ratingID {
            get {
                return this.ratingIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ratingIDField, value) != true)) {
                    this.ratingIDField = value;
                    this.RaisePropertyChanged("ratingID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string restaurantID {
            get {
                return this.restaurantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.restaurantIDField, value) != true)) {
                    this.restaurantIDField = value;
                    this.RaisePropertyChanged("restaurantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string reviewerName {
            get {
                return this.reviewerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewerNameField, value) != true)) {
                    this.reviewerNameField = value;
                    this.RaisePropertyChanged("reviewerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float ratingScore {
            get {
                return this.ratingScoreField;
            }
            set {
                if ((this.ratingScoreField.Equals(value) != true)) {
                    this.ratingScoreField = value;
                    this.RaisePropertyChanged("ratingScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.T4CsharpWebService1Uppg2Soap")]
    public interface T4CsharpWebService1Uppg2Soap {
        
        // CODEGEN: Generating message contract since element name GetRestaurantsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurants", ReplyAction="*")]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse GetRestaurants(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurants", ReplyAction="*")]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse> GetRestaurantsAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest request);
        
        // CODEGEN: Generating message contract since element name GetTableResarvationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableResarvations", ReplyAction="*")]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse GetTableResarvations(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableResarvations", ReplyAction="*")]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse> GetTableResarvationsAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest request);
        
        // CODEGEN: Generating message contract since element name GetDiningTablesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiningTables", ReplyAction="*")]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse GetDiningTables(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiningTables", ReplyAction="*")]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse> GetDiningTablesAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest request);
        
        // CODEGEN: Generating message contract since element name GetRestaurantRatingResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantRating", ReplyAction="*")]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse GetRestaurantRating(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRestaurantRating", ReplyAction="*")]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse> GetRestaurantRatingAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurants", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequestBody Body;
        
        public GetRestaurantsRequest() {
        }
        
        public GetRestaurantsRequest(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRestaurantsRequestBody {
        
        public GetRestaurantsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponseBody Body;
        
        public GetRestaurantsResponse() {
        }
        
        public GetRestaurantsResponse(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestaurantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.Restaurant[] GetRestaurantsResult;
        
        public GetRestaurantsResponseBody() {
        }
        
        public GetRestaurantsResponseBody(T4CSharpConsoleApplicationUppg2.ServiceReference1.Restaurant[] GetRestaurantsResult) {
            this.GetRestaurantsResult = GetRestaurantsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableResarvationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableResarvations", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequestBody Body;
        
        public GetTableResarvationsRequest() {
        }
        
        public GetTableResarvationsRequest(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTableResarvationsRequestBody {
        
        public GetTableResarvationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTableResarvationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTableResarvationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponseBody Body;
        
        public GetTableResarvationsResponse() {
        }
        
        public GetTableResarvationsResponse(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTableResarvationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.TableReservation[] GetTableResarvationsResult;
        
        public GetTableResarvationsResponseBody() {
        }
        
        public GetTableResarvationsResponseBody(T4CSharpConsoleApplicationUppg2.ServiceReference1.TableReservation[] GetTableResarvationsResult) {
            this.GetTableResarvationsResult = GetTableResarvationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiningTablesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiningTables", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequestBody Body;
        
        public GetDiningTablesRequest() {
        }
        
        public GetDiningTablesRequest(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDiningTablesRequestBody {
        
        public GetDiningTablesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiningTablesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiningTablesResponse", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponseBody Body;
        
        public GetDiningTablesResponse() {
        }
        
        public GetDiningTablesResponse(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiningTablesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.DiningTable[] GetDiningTablesResult;
        
        public GetDiningTablesResponseBody() {
        }
        
        public GetDiningTablesResponseBody(T4CSharpConsoleApplicationUppg2.ServiceReference1.DiningTable[] GetDiningTablesResult) {
            this.GetDiningTablesResult = GetDiningTablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantRatingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurantRating", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequestBody Body;
        
        public GetRestaurantRatingRequest() {
        }
        
        public GetRestaurantRatingRequest(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRestaurantRatingRequestBody {
        
        public GetRestaurantRatingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRestaurantRatingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRestaurantRatingResponse", Namespace="http://tempuri.org/", Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponseBody Body;
        
        public GetRestaurantRatingResponse() {
        }
        
        public GetRestaurantRatingResponse(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRestaurantRatingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.RestaurantRating[] GetRestaurantRatingResult;
        
        public GetRestaurantRatingResponseBody() {
        }
        
        public GetRestaurantRatingResponseBody(T4CSharpConsoleApplicationUppg2.ServiceReference1.RestaurantRating[] GetRestaurantRatingResult) {
            this.GetRestaurantRatingResult = GetRestaurantRatingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface T4CsharpWebService1Uppg2SoapChannel : T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class T4CsharpWebService1Uppg2SoapClient : System.ServiceModel.ClientBase<T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap>, T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap {
        
        public T4CsharpWebService1Uppg2SoapClient() {
        }
        
        public T4CsharpWebService1Uppg2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public T4CsharpWebService1Uppg2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public T4CsharpWebService1Uppg2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public T4CsharpWebService1Uppg2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetRestaurants(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest request) {
            return base.Channel.GetRestaurants(request);
        }
        
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.Restaurant[] GetRestaurants() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequestBody();
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse retVal = ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetRestaurants(inValue);
            return retVal.Body.GetRestaurantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse> T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetRestaurantsAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest request) {
            return base.Channel.GetRestaurantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsResponse> GetRestaurantsAsync() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantsRequestBody();
            return ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetRestaurantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetTableResarvations(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest request) {
            return base.Channel.GetTableResarvations(request);
        }
        
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.TableReservation[] GetTableResarvations() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequestBody();
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse retVal = ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetTableResarvations(inValue);
            return retVal.Body.GetTableResarvationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse> T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetTableResarvationsAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest request) {
            return base.Channel.GetTableResarvationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsResponse> GetTableResarvationsAsync() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetTableResarvationsRequestBody();
            return ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetTableResarvationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetDiningTables(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest request) {
            return base.Channel.GetDiningTables(request);
        }
        
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.DiningTable[] GetDiningTables() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequestBody();
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse retVal = ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetDiningTables(inValue);
            return retVal.Body.GetDiningTablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse> T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetDiningTablesAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest request) {
            return base.Channel.GetDiningTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesResponse> GetDiningTablesAsync() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetDiningTablesRequestBody();
            return ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetDiningTablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetRestaurantRating(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest request) {
            return base.Channel.GetRestaurantRating(request);
        }
        
        public T4CSharpConsoleApplicationUppg2.ServiceReference1.RestaurantRating[] GetRestaurantRating() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequestBody();
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse retVal = ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetRestaurantRating(inValue);
            return retVal.Body.GetRestaurantRatingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse> T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap.GetRestaurantRatingAsync(T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest request) {
            return base.Channel.GetRestaurantRatingAsync(request);
        }
        
        public System.Threading.Tasks.Task<T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingResponse> GetRestaurantRatingAsync() {
            T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest inValue = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequest();
            inValue.Body = new T4CSharpConsoleApplicationUppg2.ServiceReference1.GetRestaurantRatingRequestBody();
            return ((T4CSharpConsoleApplicationUppg2.ServiceReference1.T4CsharpWebService1Uppg2Soap)(this)).GetRestaurantRatingAsync(inValue);
        }
    }
}
